# Generated by Django 5.0.7 on 2024-08-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_locations_alter_flight_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
    ]
